# Generated by Django 5.2.17 on 2026-08-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='raw_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingest.rawalert'),
        ),
        migrations.AddField(
            model_name='analystaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.tenant'),
        ),
        migrations.AddField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.tenant'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['tenant', 'status', 'severity', '-occurred_at'], name='events_even_tenant__37291f_idx'),
        ),
    ]
