# Generated by Django 5.2.17 on 2026-08-25 16:49

from django.db import migrations

TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION forbid_analyst_action_change() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'analyst_action field is append-only and cannot be modified';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER analyst_action_append_only
BEFORE UPDATE OR DELETE ON events_analystaction
FOR EACH ROW EXECUTE FUNCTION forbid_analyst_action_change();
"""

DROP_SQL = """
DROP TRIGGER IF EXISTS analyst_action_append_only ON events_analystaction;
DROP FUNCTION IF EXISTS forbid_analyst_action_change();
"""

def apply_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(TRIGGER_SQL)
        
def drop_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(DROP_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(apply_trigger, drop_trigger)
    ]
