# Generated by Django 5.2.17 on 2026-08-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=200)),
                ('source_type', models.CharField(max_length=200)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', '-received_at'], name='ingest_rawa_tenant__2f8990_idx')],
            },
        ),
    ]
